# Wellknown directory
Alias /.well-known /srv/http/.well-known/
<Directory "/srv/http/.well-known">
Options None
AllowOverride None
ForceType text/plain
#RedirectMatch 404 "^(?!/\.well-known/acme-challenge/[\w-]{43}$)"
</Directory>
